# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'ToDoApp' do
  use_frameworks!
  
  # Pods for ToDoApp
  
  pod 'SwiftLint'
  
  target 'ToDoAppTests' do
    inherit! :search_paths
  end
  
  target 'ToDoAppUITests' do
  end
  
end
