platform :ios, '17.0'

target 'ToDoApp' do
  use_frameworks!

  # Pods for ToDoApp
  pod 'SwiftLint'
  
  pod 'FileCache', :path => './FileCache'
  
  target 'ToDoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoAppUITests' do
    # Pods for testing
  end

end
