platform :ios, '11.0'

target 'ToDoApp' do
  use_frameworks!

  # Pods for ToDoApp
  pod 'SwiftLint'
  pod 'SQLite.swift', '~> 0.14.0'

  target 'ToDoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoAppUITests' do
    # Pods for testing
  end

end
